# Generated by Django 3.1.2 on 2020-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201101_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(default='https://cdn.fastly.picmonkey.com/contentful/h6goo9gw1hh6/2C3VXIVGMfmU5C260BJ45t/57005d814375fdf6c6c1e7a66a3a6605/photo-editing.jpg?w=575&q=70', upload_to=''),
        ),
    ]
