# Generated by Django 3.1.2 on 2020-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201101_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(default='random.jpg', upload_to=''),
        ),
    ]
